### PR TITLE
Create MVP Snap package

### PR DESCRIPTION
**Pull request by diddledan**
- Update `setup.py` to fix the path to the entrypoint
- Add `.snapcraft.yaml` to create Snap packages

Signed-off-by: Daniel Llewellyn <daniel@bowlhat.net>

### CODE REVIEW

**Comment by Aury88** [comment]
thank you @diddledan !
I tried your changes but after the `snapcraft` command I obtain this error:
```
This part is missing libraries that cannot be satisfied with any available stage-packages known to snapcraft:
- libgdk-x11-2.0.so.0
- libgtk-x11-2.0.so.0
These dependencies can be satisfied via additional parts or content sharing. Consider validating configured filesets if this dependency was built.
Priming persepolis 
Failed to generate snap metadata: Specified command 'bin/persepolis' was not found.
Verify the command is correct and for a more deterministic outcome, specify the relative path to the command from the prime directory.
```
am I doing something wrong?

**Comment by Aury88** [comment]
after adding a "persepolis" named file in /bin containing this:
```
#!/usr/bin/env python
# Startup from system-wide installation
# Copyright (C) 2002 - 2009 John Goerzen
# <jgoerzen@complete.org>
#
#    This program is free software; you can redistribute it and/or modify ...
    import sys
    import os
    from persepolis import persepolis

    oi = persepolis.main()
    oi.run()
```
I have this error: 
```
Priming persepolis 
The command 'bin/persepolis' was not found in the prime directory, it has been changed to 'bin/persepolis'.
Failed to generate snap metadata: The specified command 'bin/persepolis' defined in the app 'persepolis' is not executable.
```
but the file is executable: 
```
~/snap/persepolis/bin$ ls -l
totale 12
-rwxrwxr-x 1 aurelio aurelio 973 apr  7 07:43 persepolis
```

**Comment by diddledan** [comment]
The changes in this PR should be sufficient to get persepolis running. You do **not** need to manually create an executable because the change to `setup.py` covers this.

**Comment by Aury88** [comment]
Hi @diddledan , Sorry but I tried your PR chages on my laptop but when I try to snapcraft I obtain the error
```
Failed to generate snap metadata: Specified command 'bin/persepolis' was not found.
Verify the command is correct and for a more deterministic outcome, specify the relative path to the command from the prime directory.
```

**Comment by diddledan** [comment]
Double check that you have both changed files from the PR and then run a `snapcraft clean` before re-running `snapcraft` in case there is some cached data from a previous run that is causing conflict.

**Comment by Aury88** [comment]
sorry, I forgot to mention that but my first message error is after a `snapcraft clean` command 
After checking the changed files I confirm that I receive the same 
[changedfiles.zip](https://github.com/Aury88/persepolis/files/4452290/changedfiles.zip)

error:
```
This part is missing libraries that cannot be satisfied with any available stage-packages known to snapcraft:
- libgdk-x11-2.0.so.0
- libgtk-x11-2.0.so.0
These dependencies can be satisfied via additional parts or content sharing. Consider validating configured filesets if this dependency was built.
Priming persepolis 
Failed to generate snap metadata: Specified command 'bin/persepolis' was not found.
Verify the command is correct and for a more deterministic outcome, specify the relative path to the command from the prime directory.
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
```

**Comment by diddledan** [comment]
Make sure you don't also have a `snap` folder in your tree.

**Comment by Aury88** [comment]
checked, but  I have no snap file or directory under the persepolis directory (the one where is located the .snapcraft.yaml file)...but the persepolis file is under a "snap" named directory...could be this?

adding a   libgtk2.0-0 under the stage-packages seems to solve the missing dependencies error but still it does not solve the problem with the  'bin/persepolis':
```
Downloading snap 'youtube-dl'
Downloading snap 'ffmpeg'
Pulling persepolis 
Building desktop-qt5 
make FLAVOR=qt5 -j2
make FLAVOR=qt5 install DESTDIR=/root/parts/desktop-qt5/install
install -D -m755 desktop-launch "/root/parts/desktop-qt5/install"/bin/desktop-launch
install -D -m644 snappy-qt5.conf \
	"/root/parts/desktop-qt5/install"/etc/xdg/qtchooser/snappy-qt5.conf
install -D -m644 snappy-qt4.conf \
	"/root/parts/desktop-qt5/install"/etc/xdg/qtchooser/snappy-qt4.conf
install -D -m644 flavor-select "/root/parts/desktop-qt5/install"/
Building persepolis 
Staging desktop-qt5 
Staging persepolis 
Priming desktop-qt5 
Priming persepolis 
Failed to generate snap metadata: Specified command 'bin/persepolis' was not found.
Verify the command is correct and for a more deterministic outcome, specify the relative path to the command from the prime directory.
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
aurelio@aurelio-Lenovo-B51-80:~/snap/persepolis$
```
or maybe the problem is caused by my distro? I'm using snapcraft, version 3.11+git34.ga0b32a89
on ubuntu 16.04

**Comment by Aury88** [comment]
was the snapcraft successful  on your computer @diddledan ? does the app launch correctly?

 I have re-tried anything but  the result is the same...I also tried to change in the setup.py the `console_scripts` string but after the `snapcraft clean` and `snapcraft` I obtain the same results:
```
Failed to generate snap metadata: Specified command 'bin/persepolis' was not found.
Verify the command is correct and for a more deterministic outcome, specify the relative path to the command from the prime directory.
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
```
the setup.py's console_scripts does not appear to affect the snapcraft output.

are you sure the snapcraft.yaml `apps` part is correct?
the snapcraft.yaml like the one in the snapcraft guided procedure has:

```
apps:
  persepolis:
    command: bin/persepolis
    command-chain: [bin/desktop-launch]

```
but unlike in that  snapcraft example in the persepolis code there is no a bin directory with an executable "persepolis" inside it, so why do we tell to snapcraft to launch the app via the executable "persepolis" in the "bin" directory?

**Comment by diddledan** [comment]
Yes the snap builds and launches with the code in my (this) PR.

**Comment by Aury88** [comment]
sorry @diddledan, I really don't understand what is wrong on my pc...my last attempt was remove snapcraft and multipass and other snaps (like the youtube-dl snap) and then reinstall snapcraft (the snap version)...after that I tried   to snapcraft persepolis but I obtain the same error ... I don't understand...

**Comment by Aury88** [comment]
Also tried to use  the snapcraft and multipass edge snaps but obtain the same result :confounded:

**Pull request merged**
